name: Build and Deploy Repository

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build package
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          build-bundle: false
          manifest-path: ru.yandex.music.yml
          gpg-sign: ${{ steps.import_gpg.outputs.keyid }}

      - name: Generate Flatpak Repo
        run: |
          flatpak build-update-repo --prune --generate-static-deltas --gpg-sign=${{ steps.import_gpg.outputs.keyid }} repo

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          keep_files: true
